/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import model.Course;
import java.util.logging.Logger;
import java.util.logging.Level;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.RowFilter;
import javax.swing.JOptionPane;
/**
 *
 * @author Asus
 */
public class CourseWindow extends javax.swing.JFrame {
   private dao.CourseDAO courseDAO = new dao.CourseDAO();
   private static final Logger logger = Logger.getLogger(CourseWindow.class.getName());
    private DefaultTableModel tableModel;
    private TableRowSorter<DefaultTableModel> sorter;
    private javax.swing.JFrame parentMenu;
    public CourseWindow(javax.swing.JFrame menu) {
    this.parentMenu = menu;
    initComponents();
    
    // Use 'tableModel' instead of 'model'
    tableModel = (DefaultTableModel) tblCourses.getModel();
    sorter = new TableRowSorter<>(tableModel);
    tblCourses.setRowSorter(sorter);

    // Call this to load existing courses immediately
    refreshCourseTable(); 

    setupSafetyGuard();
} 
private void refreshCourseTable() {
  java.util.List<model.Course> courses = courseDAO.getAllCourses();
    
    // Clear the table using our renamed variable
    tableModel.setRowCount(0); 
    
    // Loop through database results and add to table
    for (model.Course c : courses) {
        tableModel.addRow(new Object[]{
            c.getCourseId(), 
            c.getCourseName(), 
            c.getCourseDescription(), 
            c.getCredits()
        });
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCourseName = new javax.swing.JTextField();
        txtDescription = new javax.swing.JTextField();
        txtCredits = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourses = new javax.swing.JTable();
        btnAddCourse = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtCourseName.addActionListener(this::txtCourseNameActionPerformed);

        txtCredits.addActionListener(this::txtCreditsActionPerformed);

        tblCourses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Description", "Credits"
            }
        ));
        jScrollPane1.setViewportView(tblCourses);

        btnAddCourse.setText("Add Course");
        btnAddCourse.addActionListener(this::btnAddCourseActionPerformed);

        jLabel1.setText("Course Name");

        jLabel2.setText("Course Desciption");

        jLabel3.setText("Credits");

        btnUpdate.setText("Update Course");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCredits, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDescription, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCourseName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddCourse)
                            .addComponent(btnUpdate)
                            .addComponent(btnDelete))
                        .addGap(0, 6, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddCourse)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnUpdate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCredits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btnDelete))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCourseNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCourseNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCourseNameActionPerformed

    private void txtCreditsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCreditsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCreditsActionPerformed

    private void btnAddCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCourseActionPerformed
try {
        String name = txtCourseName.getText().trim();
        String desc = txtDescription.getText().trim();
        String creditsStr = txtCredits.getText().trim();

        if (name.isEmpty() || creditsStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in Name and Credits!");
            return;
        }

        int credits = Integer.parseInt(creditsStr);
        
        // This 'model.Course' now works because the variable is renamed to 'tableModel'
        model.Course c = new model.Course(0, name, desc, credits);
        
        if (courseDAO.addCourse(c)) {
            JOptionPane.showMessageDialog(this, "Course Added Successfully!");
            
            // Reload the table so the new course appears
            refreshCourseTable(); 
            
            // Clear the fields
            txtCourseName.setText("");
            txtDescription.setText("");
            txtCredits.setText("");
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Credits must be a number!");
    }
    }//GEN-LAST:event_btnAddCourseActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
    int selectedRow = tblCourses.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Select a course to update.");
        return;
    }

    // Convert view index to model index to support sorting/filtering
    int modelIndex = tblCourses.convertRowIndexToModel(selectedRow);
    int id = (int) tableModel.getValueAt(modelIndex, 0);
    String name = txtCourseName.getText().trim();
    String desc = txtDescription.getText().trim();
    int credits = Integer.parseInt(txtCredits.getText().trim());

    model.Course c = new model.Course(id, name, desc, credits);
    if (courseDAO.updateCourse(c)) {
        JOptionPane.showMessageDialog(this, "Course Updated!");
        refreshCourseTable();
    }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
    // 1. Get the selected row from the table
    int selectedRow = tblCourses.getSelectedRow();
    
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a course to delete!");
        return;
    }

    // 2. Convert index to model index (important if you use the search/sorter)
    int modelIndex = tblCourses.convertRowIndexToModel(selectedRow);
    
    // 3. Get the Course ID from the first column (index 0)
    int courseId = (int) tableModel.getValueAt(modelIndex, 0);

    // 4. Confirm deletion with the user
    int confirm = JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to delete this course?", 
            "Confirm Deletion", JOptionPane.YES_NO_OPTION);

    if (confirm == JOptionPane.YES_OPTION) {
        // 5. Call the DAO to delete from the database
        if (courseDAO.deleteCourse(courseId)) {
            JOptionPane.showMessageDialog(this, "Course Deleted Successfully!");
            refreshCourseTable(); // Refresh the GUI table
        } else {
            // This usually triggers if a foreign key constraint is violated
            JOptionPane.showMessageDialog(this, "Error: Could not delete course. It may have enrolled students.");
        }
    }
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCourse;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCourses;
    private javax.swing.JTextField txtCourseName;
    private javax.swing.JTextField txtCredits;
    private javax.swing.JTextField txtDescription;
    // End of variables declaration//GEN-END:variables
private void setupSafetyGuard() {
    this.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
    this.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosing(java.awt.event.WindowEvent e) {
            if (parentMenu != null) {
                parentMenu.setVisible(true); // Show the original menu
            }
            dispose(); // Close this window
        }
    });
}
}
