/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import database.DatabaseConnection;
import java.util.List; // FIXES LIST
import java.util.logging.Logger;
import java.util.logging.Level;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.RowFilter;
/**
 *
 * @author Asus
 */
public class EnrollmentWindow extends javax.swing.JFrame {
private dao.EnrollmentDAO enrollmentDAO = new dao.EnrollmentDAO();
private dao.StudentDAO studentDAO = new dao.StudentDAO();
private dao.CourseDAO courseDAO = new dao.CourseDAO();
private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EnrollmentWindow.class.getName());
private javax.swing.JFrame parentMenu;

public EnrollmentWindow(javax.swing.JFrame menu) {
    this.parentMenu = menu;
    initComponents();
    populateComboBoxes();
    refreshEnrollmentTable();
    setupSafetyGuard(); // Add this call
}
    private void populateComboBoxes() {

    cmbStudents.removeAllItems();
    cmbCourses.removeAllItems();

    List<model.Student> students = studentDAO.getAllStudents();
    cmbStudents.removeAllItems();
    for (model.Student s : students) {
        cmbStudents.addItem(s.getStudentId() + " - " + s.getFirstName());
    }

    // 2. Fill Courses (FIX: Complete this block)
    List<model.Course> courses = courseDAO.getAllCourses(); // Get data from DB
    cmbCourses.removeAllItems();
    for (model.Course c : courses) {
        // This adds the "ID - Name" to your empty dropdown
        cmbCourses.addItem(c.getCourseId() + " - " + c.getCourseName());
    }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbStudents = new javax.swing.JComboBox<>();
        cmbCourses = new javax.swing.JComboBox<>();
        btnEnroll = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEnrollment = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmbStudents.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbCourses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCourses.addActionListener(this::cmbCoursesActionPerformed);

        btnEnroll.setText("Enroll");
        btnEnroll.addActionListener(this::btnEnrollActionPerformed);

        tblEnrollment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblEnrollment);

        jButton1.setText("Delete");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(this::btnRefreshActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbCourses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRefresh))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbStudents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEnroll)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(cmbStudents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCourses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnroll)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnrollActionPerformed
try {
        int sId = Integer.parseInt(cmbStudents.getSelectedItem().toString().split(" - ")[0]);
        int cId = Integer.parseInt(cmbCourses.getSelectedItem().toString().split(" - ")[0]);

        // Use the DAO to check for duplicates
        if (enrollmentDAO.isAlreadyEnrolled(sId, cId)) {
            JOptionPane.showMessageDialog(this, "Student is already enrolled in this course!");
            return; 
        }

        model.Enrollment enrollment = new model.Enrollment(0, sId, cId, new java.sql.Date(System.currentTimeMillis()));
        if (enrollmentDAO.addEnrollment(enrollment)) {
            JOptionPane.showMessageDialog(this, "Enrolled Successfully!");
            refreshEnrollmentTable();
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }

    }//GEN-LAST:event_btnEnrollActionPerformed

    private void cmbCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCoursesActionPerformed
     
    }//GEN-LAST:event_cmbCoursesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    int selectedRow = tblEnrollment.getSelectedRow();
    if (selectedRow != -1) {
        int enrollmentId = (int) tblEnrollment.getValueAt(selectedRow, 0);
        int confirm = JOptionPane.showConfirmDialog(this, "Delete this enrollment?");
        if (confirm == JOptionPane.YES_OPTION) {
            enrollmentDAO.deleteEnrollment(enrollmentId);
            refreshEnrollmentTable();
        }
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnroll;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JComboBox<String> cmbCourses;
    private javax.swing.JComboBox<String> cmbStudents;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEnrollment;
    // End of variables declaration//GEN-END:variables
private void setupSafetyGuard() {
    this.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
    this.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosing(java.awt.event.WindowEvent e) {
            if (parentMenu != null) {
                parentMenu.setVisible(true);
            }
            dispose();
        }
    });
}
private void refreshEnrollmentTable() {
    try {
        // Change the List type to Object[] to match your DAO's output
        List<Object[]> enrollments = enrollmentDAO.getAllEnrollments();
        
        DefaultTableModel model = (DefaultTableModel) tblEnrollment.getModel();
        model.setRowCount(0); 

        for (Object[] row : enrollments) {
            // Directly add the row provided by the DAO
            // This assumes your DAO returns: [ID, Student Name, Course Name, Date]
            model.addRow(row);
        }
    } catch (Exception ex) {
        logger.log(Level.SEVERE, "Failed to refresh enrollment table", ex);
    }
}

public boolean isAlreadyEnrolled(int studentId, int courseId) {
    String sql = "SELECT COUNT(*) FROM Enrolled_Subject WHERE student_id = ? AND course_id = ?";
    try (Connection conn = DatabaseConnection.getConnection();
         PreparedStatement ps = conn.prepareStatement(sql)) {
        ps.setInt(1, studentId);
        ps.setInt(2, courseId);
        ResultSet rs = ps.executeQuery();
        if (rs.next()) {
            return rs.getInt(1) > 0;
        }
    } catch (SQLException e) {
        System.out.println("Check Enrollment Error: " + e.getMessage());
    }
    return false;
}

}



